@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Dec 21 12:30:20 +0100 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto eec2ad925c0e47d680bf0711a80a39bf --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot SwitchMultistadio_TB_behav xil_defaultlib.SwitchMultistadio_TB -log elaborate.log"
call xelab  -wto eec2ad925c0e47d680bf0711a80a39bf --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot SwitchMultistadio_TB_behav xil_defaultlib.SwitchMultistadio_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
