webtalk_init -webtalk_dir C:/Users/itama/Desktop/Architettura dei Sistemi Digitali/Encoder_BCD/Encoder_BCD.sim/sim_1/behav/xsim/xsim.dir/PriorityEncoder_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 27 16:13:16 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aec7ff07-5c13-485d-9d96-51a209822c33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "44bd3f913d624c1aa25ff1023d69e138" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 312908096 -regid "" -xml C:/Users/itama/Desktop/Architettura dei Sistemi Digitali/Encoder_BCD/Encoder_BCD.sim/sim_1/behav/xsim/xsim.dir/PriorityEncoder_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/itama/Desktop/Architettura dei Sistemi Digitali/Encoder_BCD/Encoder_BCD.sim/sim_1/behav/xsim/xsim.dir/PriorityEncoder_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/itama/Desktop/Architettura dei Sistemi Digitali/Encoder_BCD/Encoder_BCD.sim/sim_1/behav/xsim/xsim.dir/PriorityEncoder_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
