@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Oct 19 16:56:06 +0200 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto c933e1da10854b9eb1206050b8f1593c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Mux16_1_TB_behav xil_defaultlib.Mux16_1_TB -log elaborate.log"
call xelab  -wto c933e1da10854b9eb1206050b8f1593c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Mux16_1_TB_behav xil_defaultlib.Mux16_1_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
